<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('CourseHorse Test '); ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
                        ->prependStylesheet($this->basePath() . '/css/metro.css')
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/style_responsive.css')
                        ->prependStylesheet($this->basePath() . '/css/style_default.css')
                        ->prependStylesheet($this->basePath() . '/css/uniform.default.css')
         ?>
                        
        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                     
                                      ->prependFile($this->basePath() . '/js/jquery-1.8.3.min.js')
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.uniform.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.blockui.js')
                                      ->prependFile($this->basePath() . '/js/app.js')
                                      
        ?>

    </head>
    <?php echo $this->content; ?>
    <?php echo $this->inlineScript() ?>
      <script>
        jQuery(document).ready(function() {     
          App.initLogin();
        });
      </script>
</html>
