<!-- BEGIN BODY -->
<body class="login">
  <!-- BEGIN LOGO -->
  <div class="logo">
    <img src="assets/img/logo-big.png" alt="" /> 
  </div>
  <!-- END LOGO -->
  <!-- BEGIN LOGIN -->
  <div class="content">
    <!-- BEGIN LOGIN FORM -->
    <form id="login_form" class="form-vertical login-form" action="<?php echo $this->url('login');?>" method="post">
      <h3 class="form-title">Login to your account</h3>
      <div class="control-group">
        <div class="controls">
          <div class="input-icon left">
            <input name="email" class="m-wrap" type="text" placeholder="Email" />
          </div>
        </div>
      </div>
      <div class="control-group">
        <div class="controls">
          <div class="input-icon left">
            <input name="password" class="m-wrap" type="password" style="" placeholder="Password" />
          </div>
        </div>
      </div>
      <div class="control-group">
        <div class="controls">
          <div class="input-icon left">
            <input type="submit" value="Login"/>
          </div>
        </div>
      </div>
    </form>
    <!-- END LOGIN FORM -->        
  </div>
  <!-- END LOGIN -->
  <!-- BEGIN COPYRIGHT -->
  <div class="copyright">
    2013 &copy; Emil Diaz. CourseHorse Test.
  </div>
  <!-- END COPYRIGHT -->
</body>
<!-- END BODY -->
